# Generated by Django 5.2.7 on 2025-10-19 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_comment_parent'),
        ('taggit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug', 'published'], name='articles_ar_slug_447e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='articles_ar_created_b5cc75_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarks',
            index=models.Index(fields=['article', 'user'], name='articles_bo_article_691ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='articles_ca_slug_984c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'approved'], name='articles_co_article_0b770b_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='articles_co_parent__5bf8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['comment', 'resolved'], name='articles_co_comment_3cf18b_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['article', 'user'], name='articles_li_article_78926e_idx'),
        ),
    ]
